---

- name: Include sites-enabled
  lineinfile:
    state=present
    dest="{{nginx_prefix}}/nginx.conf"
    insertafter="include /etc/nginx/conf.d/\*\.conf;$"
    line="    include {{nginx_sites_enabled}}/*.conf;"
  notify: nginx restart

# vi:ts=2:sw=2:et:ft=yaml
