---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"

- include: install/Debian.yml
  tags: nginx_install
  when: ansible_os_family == 'Debian'

- include: install/RedHat.yml
  tags: nginx_install
  when: ansible_os_family == 'RedHat'

- include: config.yml
  tags: nginx_config

- include: ssl.yml
  tags: nginx_ssl

- include: vhosts.yml
  tags: nginx_vhosts

# vi:ts=2:sw=2:et:ft=yaml
