---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install/Debian.yml
  tags: nginx_install
  when: ansible_os_family == 'Debian'

- include: install/RedHat.yml
  tags: nginx_install
  when: ansible_os_family == 'RedHat'

- include: config.yml
  tags: nginx_config

- include: ssl.yml
  tags: nginx_ssl

- include: vhosts.yml
  tags: nginx_vhosts

- name: Start and Enable nginx
  service:
    name=nginx
    state=started
    enabled=yes
  when: nginx_enabled

# vi:ts=2:sw=2:et:ft=yaml
