---

- name: Include sites-enabled
  lineinfile:
    state=present
    dest="{{nginx_prefix}}/nginx.conf"
    insertafter="include /etc/nginx/conf.d/\*\.conf;$"
    line="    include {{nginx_sites_enabled}}/*.conf;"
  notify: nginx restart

- name: Stat default.conf
  stat: 
    path: "{{nginx_config_dir}}/default.conf"
  register: _nginx_default_conf

- name: Remove default_server config
  lineinfile:
    dest:     "{{nginx_config_dir}}/default.conf"
    regexp:   '^([\t ]*listen.*)default_server;'
    backrefs: yes
    line:     '\1;'
  when: "{{_nginx_default_conf.stat.exists}}"

# vi:ts=2:sw=2:et:ft=yaml
